# Generated by Django 5.1.1 on 2024-10-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
